resolver: lts-7.8

packages:
  - .
  - location:
      git: https://github.com/Sentenai/solr-query.git
      commit: 'c9d60b0'
    extra-dep: true
  - location:
      git: https://github.com/mitchellwrosen/riak-haskell-client
      commit: '17a68fb'
    extra-dep: true

extra-deps:
  - base-compat-0.9.1
  - protocol-buffers-2.4.0
  - protocol-buffers-descriptor-2.4.0
  - riak-protobuf-0.22.0.0
