name: riak-solr
version: 0.1.0.0
synopsis: solr-query integration for riak
description: |
  solr-query integration for riak. This is intended to replace the usage of
  searchRaw from Network.Riak.Search.
author: Mitchell Rosen
maintainer: Mitchell Rosen
github: Sentenai/riak-solr
license: BSD3
category: Network
copyright: 2016 Sentenai, Inc.

ghc-options: -Wall

default-extensions:
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - NoImplicitPrelude

dependencies:
  - base        >= 4.7   && < 5
  - base-compat >= 0.9.1

library:
  source-dirs: src
  dependencies:
    - bytestring
    - containers
    - protocol-buffers
    - riak
    - riak-protobuf
    - semigroups >= 0.3 && < 0.19
    - solr-query
    - text       >= 1.0 && < 1.3

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - riak-solr
      - hspec
