resolver: lts-16.31
allow-newer: true

extra-deps:
  - compactable-0.1.2.3 # not in resolver
  - hspec-hedgehog-0.0.1.2 # not in resolver
  - indexed-profunctors-0.1 # not in resolver
  - list-transformer-1.0.7 # not in resolver
  - pipes-interleave-1.1.3 # not in resolver
  - primitive-extras-0.8 # not in resolver
  - primitive-unlifted-0.1.1.0 # not in resolver
  - protocol-buffers-2.4.17 # resolver too new
  - protocol-buffers-descriptor-2.4.17 # protocol-buffers-2.4.11
  - stm-containers-1.1.0.4 # not in resolver
  - stm-hamt-1.2.0.4 # not in resolver
  - text-format-0.3.2
  - timezone-olson-th-0.1.0.4

  # Mitchell's library, which isn't on Hackage.
  # Use our fork for independence from his account.
  - git: git@github.com:Sentenai/json-validation
    commit: 'c46fbd26022cf6bae266c7c56547ca70c82a9b10'

  - git: git@github.com:Sentenai/true-name.git
    commit: 'cc3891544f4c520eaa012667df3e43bf6e6d2180'

  # Using our branch to get this commit:
  # https://github.com/Sentenai/thyme/commit/3ac8e91e4e477c41c6dc09e847df13359c8bb8cb
  #
  # thyme is unmaintained and deprecated in our codebase.
  # For details see: https://github.com/Sentenai/Corona/issues/851
  - git: git@github.com:Sentenai/thyme
    commit: '773dd1f45e8b69927cfcdfb17ae83dfe7d4bea63'

  # Mitchell's `pipe-stream` branch, which isn't upstreamed.
  # Use our fork for independence from his account.
  # - git: git@github.com:Sentenai/riak2-haskell-client
  #   commit: '366fe11e2b1bd200ab7364b97328ca0c5c002689'
  #   subdirs:
  #     - .
  #     - protobuf
  - git: git@github.com:Sentenai/riak2-haskell-client
    commit: '1bdc29522865a9d6c9ed9456267ecb5790351e85'
    subdirs:
        - riak
        - protobuf
        - protobuf-lens



  ### Sentenai packages

  - git: git@github.com:Sentenai/Parallax
    commit: 'a3fb860e2d93fe6d836f4820303feb69ff8fe2c2'
  - git: git@github.com:Sentenai/solr-query
    commit: '55010ca2da45a05bacbf05f25156344162577c2c'
