resolver: lts-7.8

packages:
  - .
  - location:
      git: git@github.com:Sentenai/solr-query
      commit: '9bec933'
    extra-dep: true

extra-deps:
  - bytestring-show-0.3.5.6
  - riak-1.1.1.0
  - riak-protobuf-0.22.0.0
