resolver: lts-7.8

packages:
  - .
  - location:
      git: git@github.com:Sentenai/solr-query
      commit: '8858994'
    extra-dep: true
  - location:
      git: git@github.com:mitchellwrosen/riak-haskell-client
      commit: 'e5bdf1a'
    extra-dep: true

extra-deps:
  - riak-protobuf-0.22.0.0
