resolver: lts-7.8

packages:
  - .
  - location:
      git: git@github.com:Sentenai/solr-query
      commit: '2e566b2'
    extra-dep: true
  - location:
      git: git@github.com:mitchellwrosen/riak-haskell-client
      commit: '17a68fb'
    extra-dep: true

extra-deps:
  - riak-protobuf-0.22.0.0
